# Production Profile Configuration

server:
  ssl:
    # SECURITY: HTTPS is required in production
    enabled: true
    key-store: ${SSL_KEY_STORE}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store-type: ${SSL_KEY_STORE_TYPE:PKCS12}

# Logging - Less verbose in production, focus on errors
logging:
  level:
    com.jobtracker: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    software.amazon.awssdk: ERROR

# CORS - Strict configuration in production
app:
  cors:
    # SECURITY: Only allow specific production domains
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

# Jobs seeding - Disabled in production
  jobs:
    seed:
      enabled: false

# Management endpoints - Minimal exposure in production
management:
  endpoints:
    web:
      exposure:
        # SECURITY: Only expose health and info in production
        include: health,info
  endpoint:
    health:
      # SECURITY: Don't expose detailed health info in production
      show-details: never

# Security Headers
spring:
  security:
    require-ssl: true
